/*
 * PostgreSQL option names for ClickHouse format settings.
 */

#include "postgres.h"

#include "settings.h"

/*
 * These are the FORMAT_FACTORY_SETTINGS whose canonical names start with
 * `format_` in ClickHouse 26.9. Both the canonical name and the shorter alias
 * formed by removing that prefix are accepted. Keep sorted by the declaration
 * order in ClickHouse's FormatFactorySettings.h.
 */
static const char* const prefixed_settings[] = {
    "format_csv_delimiter",
    "format_csv_allow_single_quotes",
    "format_csv_allow_double_quotes",
    "format_hive_text_rows_delimiter",
    "format_binary_max_string_size",
    "format_binary_max_array_size",
    "format_binary_max_object_size",
    "format_avro_schema_registry_url",
    "format_avro_schema_registry_connection_timeout",
    "format_avro_schema_registry_send_timeout",
    "format_avro_schema_registry_receive_timeout",
    "format_avro_schema_registry_max_retries",
    "format_avro_schema_registry_retry_initial_backoff_ms",
    "format_json_object_each_row_column_for_object_name",
    "format_csv_null_representation",
    "format_tsv_null_representation",
    "format_geojson_validate_geometry",
    "format_schema_source",
    "format_schema",
    "format_schema_message_name",
    "format_template_resultset",
    "format_template_row",
    "format_template_row_format",
    "format_template_resultset_format",
    "format_template_rows_between_delimiter",
    "format_custom_escaping_rule",
    "format_custom_field_delimiter",
    "format_custom_row_before_delimiter",
    "format_custom_row_after_delimiter",
    "format_custom_row_between_delimiter",
    "format_custom_result_before_delimiter",
    "format_custom_result_after_delimiter",
    "format_regexp",
    "format_regexp_escaping_rule",
    "format_regexp_skip_unmatched",
    "format_capn_proto_enum_comparising_mode",
    "format_capn_proto_use_autogenerated_schema",
    "format_capn_proto_max_message_size",
    "format_protobuf_use_autogenerated_schema",
    "format_display_secrets_in_show_and_select",
};

/* Format settings without an input_format_, output_format_, or format_ prefix. */
static const char* const unprefixed_settings[] = {
    "column_names_for_schema_inference",
    "schema_inference_hints",
    "schema_inference_mode",
    "schema_inference_make_columns_nullable",
    "schema_inference_make_json_columns_nullable",
    "type_json_skip_duplicated_paths",
    "type_json_allow_duplicated_key_with_literal_and_nested_object",
    "type_json_use_partial_match_to_skip_paths_by_regexp",
    "json_type_escape_dots_in_keys",
    "type_json_skip_invalid_typed_paths",
    "type_json_skip_null_typed_paths",
    "max_dynamic_subcolumns_in_json_type_parsing",
    "date_time_input_format",
    "date_time_output_format",
    "interval_output_format",
    "check_conversion_from_numbers_to_enum",
    "bool_true_representation",
    "bool_false_representation",
    "allow_special_bool_values_inside_variant",
    "errors_output_format",
    "insert_distributed_one_random_shard",
    "precise_float_parsing",
    "date_time_overflow_behavior",
    "validate_experimental_and_suspicious_types_inside_nested_types",
    "show_create_query_identifier_quoting_rule",
    "show_create_query_identifier_quoting_style",
    "into_outfile_create_parent_directories",
};

static bool
starts_with(const char* value, const char* prefix) {
    return strncmp(value, prefix, strlen(prefix)) == 0;
}

static bool
valid_setting_name(const char* value) {
    for (const unsigned char* pos = (const unsigned char*)value; *pos; pos++) {
        if (!(*pos == '_' || (*pos >= 'a' && *pos <= 'z') ||
              (*pos >= '0' && *pos <= '9'))) {
            return false;
        }
    }

    return true;
}

/* Settings required by pg_chdb's Native transport or session representation. */
bool
chdb_format_setting_protected(const char* name) {
    return starts_with(name, "input_format_native_") ||
           starts_with(name, "output_format_native_") ||
           strcmp(name, "output_format_json_quote_denormals") == 0 ||
           strcmp(name, "date_time_output_format") == 0 ||
           strcmp(name, "format_display_secrets_in_show_and_select") == 0;
}

const char*
chdb_format_setting_name(const char* option) {
    /* PostgreSQL's spelling takes precedence over the mechanical CSV alias. */
    if (strcmp(option, "delimiter") == 0) {
        return "format_csv_delimiter";
    }

    for (size_t i = 0; i < lengthof(prefixed_settings); i++) {
        const char* canonical = prefixed_settings[i];

        if (strcmp(option, canonical + 7) == 0) {
            return canonical;
        }
    }

    /* These names are self-identifying, so chDB can validate new additions. */
    if (valid_setting_name(option) &&
        (starts_with(option, "format_") || starts_with(option, "input_format_") ||
         starts_with(option, "output_format_"))) {
        return option;
    }

    for (size_t i = 0; i < lengthof(unprefixed_settings); i++) {
        if (strcmp(option, unprefixed_settings[i]) == 0) {
            return unprefixed_settings[i];
        }
    }

    return NULL;
}
