/*
 * A PostgreSQL extension for executing queries in an embedded chDB library.
 */

#include "postgres.h"

#include "miscadmin.h"
#include "utils/builtins.h"
#include <stdlib.h>
#if PG_VERSION_NUM >= 160000
#include "varatt.h"
#endif

#include "hook.h"
#include "version.h" /* Generated by Makefile. */

/* Extension metadata for the server. */
#ifdef PG_MODULE_MAGIC_EXT
PG_MODULE_MAGIC_EXT(.name = "chdb", .version = PGCHCB_VERSION);
#else
PG_MODULE_MAGIC;
#endif

void
_PG_init(void);

/*
 * _PG_init is the entry-point for the library.
 */
void
_PG_init(void) {
    if (IsBinaryUpgrade) {
        return;
    }

    InitializeUtilityHook();
}
