/*
 * A PostgreSQL extension for executing queries in an embedded chDB library.
 */

#include "postgres.h"

#include "utils/builtins.h"
#include <stdlib.h>
#if PG_VERSION_NUM >= 160000
#include "varatt.h"
#endif

/* Generated by Makefile. */
#include "version.h"

/* Extension metadata for the server. */
#ifdef PG_MODULE_MAGIC_EXT
PG_MODULE_MAGIC_EXT(.name = "chdb", .version = PGCHCB_VERSION);
#else
PG_MODULE_MAGIC;
#endif
