/*
 * A PostgreSQL extension for executing queries in an embedded chDB library.
 */

#include "postgres.h"

#include "miscadmin.h"
#include "utils/builtins.h"
#include "utils/guc.h"
#include <limits.h>

#include "hook.h"
#include "version.h" /* Generated by Makefile. */

int chdb_max_memory = 0;

/* Extension metadata for the server. */
#ifdef PG_MODULE_MAGIC_EXT
PG_MODULE_MAGIC_EXT(.name = "chdb", .version = PGCHCB_VERSION);
#else
PG_MODULE_MAGIC;
#endif

/*
 * Function returns the full chdb extension library version.
 */
PG_FUNCTION_INFO_V1(pgchdb_version);
Datum
pgchdb_version(PG_FUNCTION_ARGS) {
    PG_RETURN_TEXT_P(cstring_to_text(PGCHCB_VERSION));
}

void
_PG_init(void);

/*
 * _PG_init is the entry-point for the library.
 */
void
_PG_init(void) {
    if (IsBinaryUpgrade) {
        return;
    }

    /* A budget the helper reports as a memory-limit error. */
    DefineCustomIntVariable(
        "chdb.max_memory",
        "Memory budget for a chDB query.",
        "Zero leaves chdb to decide. Applied as max_memory_usage.",
        &chdb_max_memory,
        0,
        0,
        INT_MAX,
        PGC_SUSET,
        GUC_UNIT_MB,
        NULL,
        NULL,
        NULL
    );
    MarkGUCPrefixReserved("chdb");

    InitializeUtilityHook();
}
