#include "chdb.h"
#include "postgres.h"

/* These are always necessary for a bgworker */
#include "miscadmin.h"
#include "postmaster/bgworker.h"
#include "postmaster/interrupt.h"
#include "storage/latch.h"

/* these headers are used by this particular worker's code */
#include "access/xact.h"
#include "libpq/libpq.h"
#include "libpq/pqmq.h"
#include "storage/dsm.h"
#include "storage/ipc.h"
#include "storage/proc.h"
#include "storage/shm_toc.h"
#include "tcop/utility.h"
#include "utils/memutils.h"

#include "../version.h" /* Generated by Makefile. */
#include "worker.h"

/* Extension metadata for the server. */
#ifdef PG_MODULE_MAGIC_EXT
PG_MODULE_MAGIC_EXT(.name = "chdb_bgw", .version = PGCHCB_VERSION);
#else
PG_MODULE_MAGIC;
#endif

PGDLLEXPORT void
chdb_bgw_main(Datum main_arg);

void
chdb_bgw_main(Datum main_arg) {
    /* Establish signal handlers before unblocking signals. */
    // pqsignal(SIGHUP, SignalHandlerForConfigReload);
    pqsignal(SIGTERM, die);

    /* We're now ready to receive signals */
    BackgroundWorkerUnblockSignals();

    /* Set up a memory context to work in, just for cleanliness. */
    CurrentMemoryContext =
        AllocSetContextCreate(TopMemoryContext, "chDB worker", ALLOCSET_DEFAULT_SIZES);

    /*
     * Attach to the dynamic shared memory segment for the parallel query, and
     * find its table of contents.
     *
     * Note: at this point, we have not created any ResourceOwner in this
     * process. This will result in our DSM mapping surviving until process
     * exit, which is fine.  If there were a ResourceOwner, it would acquire
     * ownership of the mapping, but we have no need for that.
     */
    dsm_segment* seg = dsm_attach(DatumGetUInt32(main_arg));
    if (seg == NULL) {
        ereport(
            ERROR,
            errcode(ERRCODE_OBJECT_NOT_IN_PREREQUISITE_STATE),
            errmsg("could not map dynamic shared memory segment")
        );
    }
    shm_toc* toc = shm_toc_attach(CHDB_SHM_MAGIC, dsm_segment_address(seg));
    if (toc == NULL) {
        ereport(
            ERROR,
            errcode(ERRCODE_OBJECT_NOT_IN_PREREQUISITE_STATE),
            errmsg("invalid magic number in dynamic shared memory segment")
        );
    }

    /* Reconstruct the context, starting with fixed size fields in bgw_extra. */
    chdbCopyContext* ctx = palloc_object(chdbCopyContext);
    char* p              = MyBgworkerEntry->bgw_extra;
    memcpy(&ctx->db_id, p, sizeof(Oid));
    p += sizeof(Oid);
    memcpy(&ctx->role_id, p, sizeof(Oid));
    p += sizeof(Oid);
    memcpy(&ctx->scheme, p, sizeof(scheme));
    p += sizeof(scheme);
    memcpy(&ctx->is_from, p, sizeof(bool));

    /* Assemble the rest of the context from shared memory. */
    ctx->schema            = shm_toc_lookup(toc, CHDB_KEY_SCHEMA, false);
    ctx->table             = shm_toc_lookup(toc, CHDB_KEY_TABLE, false);
    ctx->url               = shm_toc_lookup(toc, CHDB_KEY_URL, false);
    ctx->access_key        = shm_toc_lookup(toc, CHDB_KEY_ACCESS_KEY, false);
    ctx->access_secret     = shm_toc_lookup(toc, CHDB_KEY_ACCESS_SECRET, false);
    ctx->session_token     = shm_toc_lookup(toc, CHDB_KEY_SESSION_TOKEN, false);
    ctx->format            = shm_toc_lookup(toc, CHDB_KEY_FORMAT, false);
    ctx->structure         = shm_toc_lookup(toc, CHDB_KEY_STRUCTURE, false);
    ctx->compression       = shm_toc_lookup(toc, CHDB_KEY_COMPRESSION, false);
    ctx->headers           = shm_toc_lookup(toc, CHDB_KEY_HEADERS, false);
    ctx->extra_credentials = shm_toc_lookup(toc, CHDB_KEY_EXTRA_CREDENTIALS, false);

    /*
     * Now we can find and attach to the error queue provided for us.  That's
     * good, because until we do that, any errors that happen here will not be
     * reported back to the process that requested that this worker be
     * launched.
     */
    shm_mq* mq = shm_toc_lookup(toc, CHDB_KEY_ERROR_QUEUE, false);
    shm_mq_set_sender(mq, MyProc);
    shm_mq_handle* mqh = shm_mq_attach(mq, seg, NULL);
    pq_redirect_to_shm_mq(seg, mqh);

    /*
     * Hooray! Primary initialization is complete.  Now, we need to set up our
     * backend-local state to match the original backend.
     */

    /*
     * Connect to the database. We skip connection authorization checks,
     * because the creator of the worker always passes the current role.
     */
    BackgroundWorkerInitializeConnectionByOid(
        ctx->db_id,
        ctx->role_id,
        BGWORKER_BYPASS_ALLOWCONN
#if PG_VERSION_NUM >= 170000
            | BGWORKER_BYPASS_ROLELOGINCHECK
#endif
    );

    /*
     * Connect to chDB. It will use a temporary directory that it cleans up
     * upon exit.
     */
    chdb_connection* conn = chdb_connect(1, (char*[]){ "chdb" });

    if (!conn) {
        ereport(
            ERROR,
            errcode(ERRCODE_CONNECTION_FAILURE),
            errmsg("unable to connect to chDB")
        );
    }

    elog(
        NOTICE,
        "%s initialized COPY %s.%s %s %s",
        MyBgworkerEntry->bgw_name,
        ctx->schema,
        ctx->table,
        ctx->is_from ? "FROM" : "TO",
        ctx->url
    );

    /* Do the work. */

    /* Report success and exit. */
    pq_putmessage(PqMsg_Terminate, NULL, 0);
    proc_exit(0);
}
