#include "chdb.h"
#include "postgres.h"

/* These are always necessary for a bgworker */
#include "miscadmin.h"
#include "postmaster/bgworker.h"
#include "postmaster/interrupt.h"
#include "storage/latch.h"

/* these headers are used by this particular worker's code */
#include "access/table.h"
#include "access/xact.h"
#include "catalog/namespace.h"
#include "libpq/libpq.h"
#include "libpq/pqmq.h"
#include "storage/ipc.h"
#include "storage/shm_toc.h"
#include "tcop/utility.h"
#include "utils/builtins.h"
#include "utils/lsyscache.h"
#include "utils/memutils.h"
#include "utils/rel.h"
#if PG_VERSION_NUM >= 190000
#include "storage/proc.h"
#endif

#include "../version.h" /* Generated by Makefile. */
#include "worker.h"

/* Extension metadata for the server. */
#ifdef PG_MODULE_MAGIC_EXT
PG_MODULE_MAGIC_EXT(.name = "chdb_bgw", .version = PGCHCB_VERSION);
#else
PG_MODULE_MAGIC;
#endif

/*
 * Decomposition of an Azure URL into the arguments that `azureBlobStorage()`
 * expects.
 */
typedef struct azureURLParts {
    char* account_url;
    char* container;
    char* path;
} azureURLParts;

/* Main entrypoint for worker execution. */
PGDLLEXPORT void
chdb_bgw_main(Datum main_arg);

/* Creates the chDB query for a COPY. */
size_t
make_ch_query(chdbCopyContext* ctx, StringInfo query, char** names, char** values);

/* Creates the Postgres query for a COPY. */
void
make_pg_query(chdbCopyContext* ctx, Relation rel, StringInfo query);

/* Parses `url` into `parts`. */
static void
parse_azure_url(char* url, azureURLParts* parts);

static char*
get_local_path_from_file_url(const char* url);

static void
chdb_conn_free(void*);

inline static void
chdb_conn_free(void* c) {
    chdb_close_conn((chdb_connection*)c);
}

static char*
generate_relation_name(Relation rel);
void
chdb_bgw_main(Datum main_arg) {
    /* Establish signal handlers before unblocking signals. */
    // pqsignal(SIGHUP, SignalHandlerForConfigReload);
    pqsignal(SIGTERM, die);

    /* We're now ready to receive signals */
    BackgroundWorkerUnblockSignals();

    /* Set up a memory context to work in, just for cleanliness. */
    CurrentMemoryContext =
        AllocSetContextCreate(TopMemoryContext, "chDB worker", ALLOCSET_DEFAULT_SIZES);

    /*
     * Attach to the dynamic shared memory segment for the parallel query, and
     * find its table of contents.
     *
     * Note: at this point, we have not created any ResourceOwner in this
     * process. This will result in our DSM mapping surviving until process
     * exit, which is fine.  If there were a ResourceOwner, it would acquire
     * ownership of the mapping, but we have no need for that.
     */
    dsm_segment* seg = dsm_attach(DatumGetUInt32(main_arg));
    if (seg == NULL) {
        ereport(
            ERROR,
            errcode(ERRCODE_OBJECT_NOT_IN_PREREQUISITE_STATE),
            errmsg("could not map dynamic shared memory segment")
        );
    }
    shm_toc* toc = shm_toc_attach(CHDB_SHM_MAGIC, dsm_segment_address(seg));
    if (toc == NULL) {
        ereport(
            ERROR,
            errcode(ERRCODE_OBJECT_NOT_IN_PREREQUISITE_STATE),
            errmsg("invalid magic number in dynamic shared memory segment")
        );
    }

    /* Reconstruct the context, starting with fixed size fields in bgw_extra. */
    chdbCopyContext* ctx = palloc_object(chdbCopyContext);
    memcpy(&ctx->extra, MyBgworkerEntry->bgw_extra, sizeof(chdbCopyExtra));

    /* Assemble the rest of the context from shared memory. */
    ctx->url           = shm_toc_lookup(toc, CHDB_KEY_URL, false);
    ctx->access_key    = shm_toc_lookup(toc, CHDB_KEY_ACCESS_KEY, false);
    ctx->access_secret = shm_toc_lookup(toc, CHDB_KEY_ACCESS_SECRET, false);
    ctx->session_token = shm_toc_lookup(toc, CHDB_KEY_SESSION_TOKEN, false);
    ctx->format        = shm_toc_lookup(toc, CHDB_KEY_FORMAT, false);
    ctx->structure     = shm_toc_lookup(toc, CHDB_KEY_STRUCTURE, false);
    ctx->compression   = shm_toc_lookup(toc, CHDB_KEY_COMPRESSION, false);

    /*
     * Now we can find and attach to the error queue provided for us.  That's
     * good, because until we do that, any errors that happen here will not be
     * reported back to the process that requested that this worker be
     * launched.
     */
    shm_mq* mq = shm_toc_lookup(toc, CHDB_KEY_ERROR_QUEUE, false);
    shm_mq_set_sender(mq, MyProc);
    shm_mq_handle* mqh = shm_mq_attach(mq, seg, NULL);
    pq_redirect_to_shm_mq(seg, mqh);

    /*
     * Hooray! Primary initialization is complete.  Now, we need to set up our
     * backend-local state to match the original backend.
     */

    /*
     * Connect to the database. We skip connection authorization checks,
     * because the creator of the worker always passes the current role.
     */
    BackgroundWorkerInitializeConnectionByOid(
        ctx->extra.db_id,
        ctx->extra.role_id,
        BGWORKER_BYPASS_ALLOWCONN
#if PG_VERSION_NUM >= 170000
            | BGWORKER_BYPASS_ROLELOGINCHECK
#endif
    );

    /*
     * Connect to chDB. It will use a temporary directory that it cleans up
     * upon exit.
     */
    chdb_connection* conn = chdb_connect(1, (char*[]){ "chdb" });

    if (!conn) {
        ereport(
            ERROR,
            errcode(ERRCODE_CONNECTION_FAILURE),
            errmsg("unable to connect to chDB")
        );
    }

    /* Set up a callback to release the connection when we're done. */
    MemoryContextCallback cleanup = { 0 };
    cleanup.func                  = chdb_conn_free;
    cleanup.arg                   = conn;
    MemoryContextRegisterResetCallback(CurrentMemoryContext, &cleanup);

    /* Assemble the chDB query. */
    StringInfoData ch_query;
    char* names[CHDB_MAX_TABLEFUNC_ARGS];
    char* values[CHDB_MAX_TABLEFUNC_ARGS];
    size_t param_count;
    initStringInfo(&ch_query);
    param_count = make_ch_query(ctx, &ch_query, names, values);

    /* Reassemble params for testing. */
    StringInfoData params;
    initStringInfo(&params);
    bool first = true;
    for (size_t i = 0; i < param_count; i++) {
        if (!first) {
            appendStringInfoString(&params, ", ");
        }
        appendStringInfo(&params, "%s: \"%s\"", names[i], values[i]);
        first = false;
    }

    elog(NOTICE, "CH QUERY: %s\nPARAMS: %s", ch_query.data, params.data);

    StartTransactionCommand();
    Relation rel = table_open(
        ctx->extra.rel_id, ctx->extra.is_from ? AccessShareLock : RowExclusiveLock
    );

    /* Assemble the Postgres query. */
    StringInfoData pg_query;
    initStringInfo(&pg_query);
    make_pg_query(ctx, rel, &pg_query);
    elog(NOTICE, "PG QUERY: %s", pg_query.data);
    const char* error;
    chdb_result* result;

    /* [Complete List of
     * Formats](https://github.com/chdb-io/chdb/blob/main/refs/clickhouse-formats-settings.md#complete-format-names-table)
     */
    if (ctx->extra.is_from) {
        /* Start streaming the chDB query. */
        result = chdb_stream_query_with_params(
            *conn,
            ch_query.data,
            "TSV", /* Compatible with COPY's text format */
            (const char* const*)names,
            (const char* const*)values,
            param_count
        );

        if (!result) {
            ereport(
                ERROR,
                errcode(ERRCODE_EXTERNAL_ROUTINE_EXCEPTION),
                errmsg("error executing chDB query"),
                errcontext("query: %s", ch_query.data)
            );
        }

        /* Check for errors. */
        if ((error = chdb_result_error(result))) {
            error = pstrdup(error);
            chdb_destroy_query_result(result);
            ereport(
                ERROR,
                errcode(ERRCODE_EXTERNAL_ROUTINE_EXCEPTION),
                errmsg("error executing chDB query"),
                errdetail("%s", error),
                errcontext("query: %s", ch_query.data)
            );
        }

        /* Process chunks. */
        while (true) {
            CHECK_FOR_INTERRUPTS();
            chdb_result* chunk = chdb_stream_fetch_result(*conn, result);
            if (!chunk) {
                break;
            }

            if ((error = chdb_result_error(chunk))) {
                /* Cut out the request ID line if present. */
                char* rec_id = strstr(error, "Request ID:");
                if (rec_id) {
                    char* end = (char*)error + strlen(error) + 1;
                    char* c   = rec_id;
                    while (c < end && *c != '\n') {
                        c++;
                    }
                    if (c < end) {
                        memmove(rec_id, c + 1, strlen(c + 1) + 1);
                    }
                }
                ereport(
                    ERROR,
                    errcode(ERRCODE_EXTERNAL_ROUTINE_EXCEPTION),
                    errmsg("error fetching chDB query result"),
                    errdetail("%s", error),
                    errcontext("query: %s", ch_query.data)
                );
            }

            /* Check if we have data in this chunk. */
            size_t chunk_length = chdb_result_length(chunk);
            if (chunk_length == 0) {
                chdb_destroy_query_result(chunk);
                break; /* End of stream */
            }

            /* Send the chunk to the Postgres table */
            char* data = chdb_result_buffer(chunk);
            elog(NOTICE, "CHUNK: %.*s", (int)chdb_result_length(chunk), data);
            chdb_destroy_query_result(chunk);
        }

        /* Cleanup streaming query. */
        chdb_destroy_query_result(result);
    } else {
        /* Start the streaming insert. */
        chdb_insert_stream stream = chdb_stream_insert(*conn, ch_query.data, "TSV");

        /* Check for errors. */
        if ((error = chdb_stream_insert_error(stream))) {
            error = pstrdup(error);
            chdb_destroy_insert_stream(stream);
            ereport(
                ERROR,
                errcode(ERRCODE_EXTERNAL_ROUTINE_EXCEPTION),
                errmsg("error executing chDB query"),
                errdetail("ERR: %s", error),
                errcontext("query: %s", ch_query.data)
            );
        }

        /* Stream results from Postgres to chDB. */
        const char* rec = NULL;
        while ((rec)) {
            CHECK_FOR_INTERRUPTS();
            if (chdb_stream_append(stream, rec, strlen(rec)) != CHDBSuccess) {
                error = pstrdup(chdb_stream_insert_error(stream));
                chdb_stream_cancel_insert(stream);
                chdb_destroy_insert_stream(stream);
                ereport(
                    ERROR,
                    errcode(ERRCODE_EXTERNAL_ROUTINE_EXCEPTION),
                    errmsg("error appending to chDB query"),
                    errdetail("%s", error),
                    errcontext("query: %s", ch_query.data)
                );
            }
        }

        /* Tell chDB the insert is done. */
        result = chdb_stream_done(stream);
        if ((error = chdb_result_error(result))) {
            error = pstrdup(error);
            chdb_destroy_query_result(result);
            chdb_destroy_insert_stream(stream);
            ereport(
                ERROR,
                errcode(ERRCODE_EXTERNAL_ROUTINE_EXCEPTION),
                errmsg("error finishing chDB query"),
                errdetail("%s", error),
                errcontext("query: %s", ch_query.data)
            );
        }

        /* Cleanup streaming insert. */
        chdb_destroy_query_result(result);
        chdb_destroy_insert_stream(stream);
    }

    /* Report success and exit. */
    table_close(rel, NoLock);
    CommitTransactionCommand();
    pq_putmessage(PqMsg_Terminate, NULL, 0);
    proc_exit(0);
}

/* Convenience constant function to append a parameter to a query. */
#define PARAM(format, name, val)                                                       \
    Assert(i + 1 <= CHDB_MAX_TABLEFUNC_ARGS);                                          \
    appendStringInfoString(query, format);                                             \
    names[i]  = name;                                                                  \
    values[i] = val;                                                                   \
    i++;

/* Default chDB query settings. */
static const char settings[] = "date_time_output_format='iso'";

size_t
make_ch_query(chdbCopyContext* ctx, StringInfo query, char** names, char** values) {
    /* Start the query. */
    appendStringInfo(
        query,
        "%s %s(",
        ctx->extra.is_from ? "SELECT * FROM" : "INSERT INTO FUNCTION",
        table_function[ctx->extra.scheme]
    );

    /*
     * TODO: For streaming queries, the buffer is sized to fit one block of
     * output: each fetch returns up to max_block_size rows (default 65409).
     * Consider estimating row size and adjusting the batch size accordingly.
     * Use `SETTINGS max_block_size = N` to set it per-query.
     */

    size_t i = 0;

    switch (ctx->extra.scheme) {
    case s3_scheme:
    case gcs_scheme:
        /*
         * https://clickhouse.com/docs/sql-reference/table-functions/s3#syntax
         * https://clickhouse.com/docs/sql-reference/table-functions/gcs#syntax
         */

        /* First parameter: the base URL. */
        if (ctx->extra.scheme == s3_scheme) {
            PARAM("{url:String}", "url", ctx->url);
        } else {
            char* uri = strstr(ctx->url, "://");
            if (!uri) {
                /* Should not happen, validated by the hook. */
                elog(ERROR, "chdb: malformed GCS URL %s ", ctx->url);
            }
            PARAM("{url:String}", "url", psprintf("https%s", uri));
        }

        if (ctx->access_key[0] != '\0') {
            /* access_key implies access secret and maybe s3 session_token. */
            PARAM(", {access_key:String}", "access_key", ctx->access_key);
            PARAM(", {access_secret:String}", "access_secret", ctx->access_secret);
            if (ctx->session_token[0] != '\0' && ctx->extra.scheme == s3_scheme) {
                PARAM(", {session_token:String}", "session_token", ctx->session_token);
            }
        }

        /* Append remaining arguments and settings. */
        if (ctx->compression[0] != '\0') {
            PARAM(", {format:String}", "format", ctx->format[0] ? ctx->format : "auto");
            PARAM(
                ", {structure:String}",
                "structure",
                ctx->structure[0] ? ctx->structure : "auto"
            );
            PARAM(", {compression:String}", "compression", ctx->compression);
        } else if (ctx->structure[0] != '\0') {
            PARAM(", {format:String}", "format", ctx->format[0] ? ctx->format : "auto");
            PARAM(", {structure:String}", "structure", ctx->structure);
        } else if (ctx->format[0] != '\0') {
            PARAM(", {format:String}", "format", ctx->format);
        }
        appendStringInfo(
            query,
            ") SETTINGS %s, s3_request_timeout_ms = %u",
            settings,
            ctx->extra.timeout
        );
        break;
    case http_scheme:
        /* https://clickhouse.com/docs/sql-reference/table-functions/url#syntax */

        /* First parameter: the base URL. */
        PARAM("{url:String}", "url", ctx->url);

        if (ctx->structure[0] != '\0') {
            PARAM(", {format:String}", "format", ctx->format[0] ? ctx->format : "auto");
            PARAM(", {structure:String}", "structure", ctx->structure);
        } else if (ctx->format[0] != '\0') {
            PARAM(", {format:String}", "format", ctx->format);
        }
        appendStringInfo(
            query,
            ") SETTINGS %s, http_connection_timeout=%u, http_max_tries=1",
            settings,
            ctx->extra.timeout / 1000
        );
        break;
    case abs_scheme: {
        /*
         * https://clickhouse.com/docs/sql-reference/table-functions/azureBlobStorage#syntax
         */

        /* Parse the Azure URL to get the account URL, container, and path. */
        azureURLParts parts;
        parse_azure_url(ctx->url, &parts);

        /* Append required args. */
        PARAM("{url:String}", "url", parts.account_url);
        PARAM(", {container:String}", "container", parts.container);
        PARAM(", {path:String}", "path", parts.path);
        PARAM(", {account_name:String}", "account_name", ctx->access_key);
        PARAM(", {account_key:String}", "account_key", ctx->access_secret);

        /* Append remaining arguments (different order from the others) and settings. */
        if (ctx->structure[0] != '\0') {
            PARAM(", {format:String}", "format", ctx->format[0] ? ctx->format : "auto");
            PARAM(", {compression:String}", "compression", ctx->compression);
            PARAM(", {structure:String}", "structure", ctx->structure);
        } else if (ctx->compression[0] != '\0') {
            PARAM(", {format:String}", "format", ctx->format[0] ? ctx->format : "auto");
            PARAM(", {compression:String}", "compression", ctx->compression);
        } else if (ctx->format[0] != '\0') {
            PARAM(", {format:String}", "format", ctx->format);
        }
        appendStringInfo(
            query,
            ") SETTINGS %s, azure_request_timeout_ms=%u",
            settings,
            ctx->extra.timeout
        );
        break;
    }
    case file_scheme:
        /* https://clickhouse.com/docs/sql-reference/table-functions/file#syntax */

        /* First parameter: the path to the file. */
        PARAM("{path:String}", "path", get_local_path_from_file_url(ctx->url));

        /* Append remaining arguments and settings. */
        if (ctx->compression[0] != '\0') {
            PARAM(", {format:String}", "format", ctx->format[0] ? ctx->format : "auto");
            PARAM(
                ", {structure:String}",
                "structure",
                ctx->structure[0] ? ctx->structure : "auto"
            );
            PARAM(", {compression:String}", "compression", ctx->compression);
        } else if (ctx->structure[0] != '\0') {
            PARAM(", {format:String}", "format", ctx->format[0] ? ctx->format : "auto");
            PARAM(", {structure:String}", "structure", ctx->structure);
        } else if (ctx->format[0] != '\0') {
            PARAM(", {format:String}", "format", ctx->format);
        }
        appendStringInfo(query, ") SETTINGS %s", settings);
        break;
    case hdfs_scheme:
        /* https://clickhouse.com/docs/sql-reference/table-functions/hdfs#syntax */

        /* First parameter: the base URL. */
        PARAM("{url:String}", "url", ctx->url);

        /* Append remaining arguments and settings. */
        if (ctx->structure[0] != '\0') {
            PARAM(", {format:String}", "format", ctx->format[0] ? ctx->format : "auto");
            PARAM(", {structure:String}", "structure", ctx->structure);
        } else if (ctx->format[0] != '\0') {
            PARAM(", {format:String}", "format", ctx->format);
        }
        appendStringInfo(query, ") SETTINGS %s", settings);
        break;
    default:
        elog(ERROR, "unsupported URL scheme %d", ctx->extra.scheme);
        break;
    }

    return i;
}

void
make_pg_query(chdbCopyContext* ctx, Relation rel, StringInfo query) {
    /*
     * Just copy the whole table for now; will deal with the COPY TO query and
     * WHERE option, if present, later.
     */
    appendStringInfo(
        query,
        "COPY %s %s STD%s (FORMAT text);",
        generate_relation_name(rel),
        ctx->extra.is_from ? "FROM" : "TO",
        ctx->extra.is_from ? "IN" : "OUT"
    );
}

/*
* Decomposition of an Azure URL into the arguments the `azureBlobStorage`
  engine expects.
*/
static void
parse_azure_url(char* url, azureURLParts* parts) {
    /*
     * Based on Azure URL parsing for the url() function in ClickHouse 26.7:
     * https://github.com/ClickHouse/ClickHouse/blob/0b235b0/src/Storages/StorageURL.cpp#L2016-L2087
     */
    char* uri = strstr(url, "://");
    if (!uri) {
        /* Should not happen, validated by the hook. */
        elog(ERROR, "chdb: malformed Azure URL %s ", url);
    }

    uri += 3;

    /// Split off the query string (a SAS token such as `?sp=...&sig=...`)
    /// before parsing the host and path.
    char* query = strchr(uri, '?');
    if (query) {
        /* NUL terminate the URL and split off the query. */
        *query = '\0';
        query++;
    }

    /*
     * `<account>.blob.core.windows.net/<container>/<blob>` or
     * `<host>/<container>/<blob>`.
     */
    char* path = strstr(uri, "/");

    /*
     * `az://<account>.blob.core.windows.net/<container>/<blob>` or
     * `azure://<host>/<container>/<blob>`
     */
    const char* host = path ? pnstrdup(uri, path - uri) : uri;
    path             = path ? path + 1 : "";

    char* dot = strchr(host, '.');
    if (!dot) {
        ereport(
            ERROR,
            errcode(ERRCODE_INVALID_PARAMETER_VALUE),
            errmsg("chdb: Azure URL missing the storage account host"),
            errhint("az://<account>.blob.core.windows.net/<container>/<path>")
        );
    }

    parts->account_url =
        query ? psprintf("https://%s?%s", host, query) : psprintf("https://%s", host);
    char* slash = strchr(path, '/');
    parts->container =
        slash ? pnstrdup(path, slash - path) : pnstrdup(path, strlen(path));
    parts->path = slash ? slash + 1 : "";

    if (strlen(parts->container) == 0) {
        ereport(
            ERROR,
            errcode(ERRCODE_INVALID_PARAMETER_VALUE),
            errmsg("chdb: Azure URL missing the container name"),
            errhint("az://<account>.blob.core.windows.net/<container>/<path>")
        );
    }
}

/*
 * Get the local path from a file:// URL. Must be an absolute path or else it
 * raises an error.
 */
static char*
get_local_path_from_file_url(const char* url) {
    /* https://github.com/ClickHouse/ClickHouse/blob/0b235b0/src/Storages/StorageURL.cpp#L2000-L2014*/
    char* path = strstr(url, "://");
    if (!path) {
        /* Should not happen, validated by the hook. */
        elog(ERROR, "chdb: malformed file URL %s ", url);
    }

    path += 3;
    if (!is_absolute_path(path)) {
        ereport(
            ERROR,
            errcode(ERRCODE_INVALID_NAME),
            errmsg("chdb: relative path not allowed for COPY to file URL")
        );
    }

    return path;
}

/*
 * generate_relation_name - copied from dblink.c
 *		Compute the name to display for a relation
 *
 * The result includes all necessary quoting and schema-prefixing.
 */
static char*
generate_relation_name(Relation rel) {
    char* nspname = RelationIsVisible(RelationGetRelid(rel))
                        ? NULL
                        : get_namespace_name(rel->rd_rel->relnamespace);
    return quote_qualified_identifier(nspname, RelationGetRelationName(rel));
}
