
#include "postgres.h"

/* These are always necessary for a bgworker */
#include "miscadmin.h"
#include "postmaster/bgworker.h"
#include "postmaster/interrupt.h"
#include "storage/latch.h"

/* these headers are used by this particular worker's code */
#include "access/xact.h"
#include "tcop/utility.h"

// #include "catalog/pg_database.h"
// #include "executor/spi.h"
// #include "fmgr.h"
// #include "lib/stringinfo.h"
// #include "pgstat.h"
// #include "utils/acl.h"
// #include "utils/builtins.h"
// #include "utils/snapmgr.h"
// #include "utils/wait_event.h"

#include "../version.h" /* Generated by Makefile. */
#include "worker.h"

/* Extension metadata for the server. */
#ifdef PG_MODULE_MAGIC_EXT
PG_MODULE_MAGIC_EXT(.name = "chdb_bgw", .version = PGCHCB_VERSION);
#else
PG_MODULE_MAGIC;
#endif

PGDLLEXPORT void
chdb_bgw_main(Datum main_arg);

void
chdb_bgw_main(Datum main_arg) {
    /* Grab the context for the work. */
    chdbCopyContext* ctx = palloc_object(chdbCopyContext);
    memcpy(ctx, MyBgworkerEntry->bgw_extra, sizeof(chdbCopyContext));

    /* Establish signal handlers before unblocking signals. */
    pqsignal(SIGHUP, SignalHandlerForConfigReload);
    pqsignal(SIGTERM, die);

    /* We're now ready to receive signals */
    BackgroundWorkerUnblockSignals();

    /*
     * Connect to the database. We skip connection authorization checks,
     * because the creator of the worker always passes the current role.
     */
    BackgroundWorkerInitializeConnectionByOid(
        ctx->dboid,
        ctx->roleoid,
        BGWORKER_BYPASS_ALLOWCONN
#if PG_VERSION_NUM >= 170000
            | BGWORKER_BYPASS_ROLELOGINCHECK
#endif
    );

    elog(
        LOG,
        "%s initialized with %s.%s",
        MyBgworkerEntry->bgw_name,
        ctx->schema,
        ctx->table
    );

    /* Do the work. */
}
