name: ✅ CI
on:
  push:
    branches: [main, wip/**]
  pull_request:
  schedule:
    - cron: "0 12 10 * *" # Monthly at noon on the tenth
jobs:
  build:
    permissions:
      contents: read
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        pg: [19, 18, 17, 16]
        arch: [amd64, arm64]
    name: 🐘 PostgreSQL ${{ matrix.pg }} ${{ matrix.arch == 'amd64' && '🧰' || '🦾' }} ${{ matrix.arch }}
    runs-on: ubuntu-${{ matrix.arch == 'amd64' && 'latest' || '24.04-arm' }}
    env: { chdb_version: v26.7.0 }
    services:
      kv-rest:
        image: ghcr.io/theory/kv-rest
        ports: [80]
    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v7
        with: { submodules: recursive }
      - name: Start Postgres ${{ matrix.pg }}
        uses: ./.github/actions/setup-pg
        with:
          version: ${{ matrix.pg }}
          packages: libkrb5-dev libipc-run-perl
      - name: Tweak Permissions # for cache restore
        run: sudo chmod a+rwx /usr/local/lib /usr/local/include
      - name: Cache chDB
        id: cache-chdb
        uses: actions/cache@v6
        with:
          key: chdb-${{ env.chdb_version }}-${{ runner.os }}-${{ runner.arch }}
          path: |
            /usr/local/lib/libchdb.so
            /usr/local/include/chdb.*
      - name: Install chDB
        run: ${{ steps.cache-chdb.outputs.cache-hit != 'true' && 'curl -sL https://lib.chdb.io | sudo -E bash' || 'sudo ldconfig' }}
        env: { INSTALL_VERSION: "${{ env.chdb_version }}" }
      - run: sudo chmod +r /usr/local/include/chdb.*
      - name: Build
        run: make -j $(nproc)
      - name: Install
        run: sudo make install
      - name: Configure AWS credentials # for s3.sql round-trip test
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ secrets.aws_role_to_assume }}
          role-session-name: ${{ github.run_id }}
          aws-region: us-east-2
      - name: Test
        run: make installcheck
        # https://console.cloud.google.com/storage/settings;tab=interoperability?project=ch-pg-test
        env:
          CLOUDSDK_AUTH_HMAC_KEY: ${{ secrets.gcp_hmac_key }}
          CLOUDSDK_AUTH_HMAC_SECRET: ${{ secrets.gcp_hmac_secret }}
          PG_CHDB_HTTP_URL: http://localhost:${{ job.services.kv-rest.ports[80] }}
      - name: Show Diffs
        if: failure()
        run: find . -name regression.diffs -exec cat {} +
      - name: Upload Diffs
        if: failure()
        uses: actions/upload-artifact@v7
        with:
          name: regression-diffs-pg${{ matrix.pg }}
          path: regression.diffs
