name: ✅ CI
on:
  push:
    branches: [main, wip/**]
  pull_request:
  schedule:
    - cron: "0 12 10 * *" # Monthly at noon on the tenth
jobs:
  build:
    permissions:
      contents: read
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        pg: [19, 18, 17, 16]
        arch: [amd64, arm64]
        build: [dynamic, static]
    name: 🐘 PgSQL ${{ matrix.pg }} ${{ matrix.arch == 'amd64' && '🧰' || '🦾' }} ${{ matrix.arch }} ${{ matrix.build }}
    runs-on: ubuntu-${{ matrix.arch == 'amd64' && 'latest' || '24.04-arm' }}
    env: { BUNDLE_LIBCHDB: 1, LIBCHDB_BUILD: "${{ matrix.build }}" }
    services:
      kv-rest:
        image: ghcr.io/theory/kv-rest
        ports: [80]
    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v7
        with: { submodules: recursive }
      - name: Start Postgres ${{ matrix.pg }}
        uses: ./.github/actions/setup-pg
        with:
          version: ${{ matrix.pg }}
          packages: libkrb5-dev libipc-run-perl
      # make BUNDLE_LIBCHDB=1 installs libchdb if missing.
      - name: Get chDB Version
        id: chdb
        run: make libchdb-variables >> $GITHUB_OUTPUT
      - name: Cache chDB
        id: cache-chdb
        uses: actions/cache@v6
        with:
          key: ${{ steps.chdb.outputs.directory }}-${{ matrix.build }}
          path: |
            ${{ steps.chdb.outputs.directory }}/lib/libchdb.*
            ${{ steps.chdb.outputs.directory }}/include/chdb.h
      - name: Build
        run: make -j $(nproc)
      - name: Install
        run: sudo --preserve-env=BUNDLE_LIBCHDB,LIBCHDB_BUILD make install
      - name: Configure AWS credentials # for s3.sql round-trip test
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ secrets.aws_role_to_assume }}
          role-session-name: ${{ github.run_id }}
          aws-region: us-east-2
      - name: Test
        run: make installcheck
        # https://console.cloud.google.com/storage/settings;tab=interoperability?project=ch-pg-test
        env:
          CLOUDSDK_AUTH_HMAC_KEY: ${{ secrets.gcp_hmac_key }}
          CLOUDSDK_AUTH_HMAC_SECRET: ${{ secrets.gcp_hmac_secret }}
          PG_CHDB_HTTP_URL: http://localhost:${{ job.services.kv-rest.ports[80] }}
      - name: Show Diffs
        if: failure()
        run: find . -name regression.diffs -exec cat {} +
      - name: Upload Diffs
        if: failure()
        uses: actions/upload-artifact@v7
        with:
          name: regression-diffs-pg${{ matrix.pg }}
          path: regression.diffs
