name: 🚀 Release
on:
  push:
    branches: [main, wip/**]
    tags: ["v[0-9]+.[0-9]+.[0-9]+"]
  pull_request:
jobs:
  release:
    name: Release on GitHub and PGXN
    runs-on: ubuntu-latest
    container: pgxn/pgxn-tools
    env: { pg: 19, chdb_version: v26.5.1-rc.3 }
    steps:
      - name: Check out the repo
        uses: actions/checkout@v7
        with: { submodules: recursive }
      - name: Start Postgres
        run: pg-start ${{ env.pg }} libkrb5-dev
      - name: Tweak Permissions # for cache restore
        run: sudo chmod a+rwx /usr/local/lib /usr/local/include
      - name: Cache chDB
        id: cache-chdb
        uses: actions/cache@v6
        with:
          key: chdb-${{ env.chdb_version }}-${{ runner.os }}-${{ runner.arch }}
          path: |
            /usr/local/lib/libchdb.so
            /usr/local/include/chdb.*
      - name: Install chDB
        run: ${{ steps.cache-chdb.outputs.cache-hit != 'true' && 'curl -sL https://lib.chdb.io | sudo -E bash' || 'sudo ldconfig' }}
        env: { INSTALL_VERSION: "${{ env.chdb_version }}" }
      - name: Bundle the Release
        id: bundle
        run: pgxn-bundle
      # - name: Test the Bundle
      #   run: make dist-test
      - name: Release on PGXN
        if: startsWith( github.ref, 'refs/tags/v' )
        env:
          PGXN_USERNAME: ${{ secrets.PGXN_USERNAME }}
          PGXN_PASSWORD: ${{ secrets.PGXN_PASSWORD }}
        run: pgxn-release
      - name: Generate Release Notes
        id: notes
        uses: theory/changelog-version-notes-action@v0
        if: startsWith( github.ref, 'refs/tags/v' )
      - name: Create GitHub Release
        if: startsWith( github.ref, 'refs/tags/v' )
        uses: softprops/action-gh-release@v2
        with:
          name: "Release ${{ github.ref_name }}"
          body_path: "${{ steps.notes.outputs.file }}"
          files: ${{ steps.bundle.outputs.bundle }}
